### ISSUE TITLE
Discuss front-end approach/needs

### ISSUE THREAD

**Issue by ismay** [dhis2/sms-configuration-app#1]
See: https://jira.dhis2.org/browse/DHIS2-8751

In a similar manner to the who-data-quality-app issue @Mohammer5 opened, I thought we could gather our thoughts on the front-end approach/planning to the sms-app here. Afterwards we can open an epic in Jira with the results.

**Comment by Mohammer5** [comment]
As discussed during the meeting, I think this is the process we've ended up with:

## We work on the app section by section

This allows us to have multiple developers work on the app without having to align too much (general architecture & state have to be aligned, although this will be mostly done through the app-runtime's data engine, so we probably won't need global state)

## Specs first

Before working on a section, a set of feature files has to be worked out / created which gives us a well defined scope / boundaries, so do exactly what's expected.

<hr />

Mostly likely I will be the first one to have time to start with the first section. I'll then go ahead and extract the features of the first section that we can discuss. We could/should ask @cooper-joe to have a look at the specs & app before we start coding.

**Comment by ismay** [comment]
> As discussed during the meeting, I think this is the process we've ended up with:
> ## We work on the app section by section
> 
> This allows us to have multiple developers work on the app without having to align too much (general architecture & state have to be aligned, although this will be mostly done through the app-runtime's data engine, so we probably won't need global state)
> ## Specs first
> 
> Before working on a section, a set of feature files has to be worked out / created which gives us a well defined scope / boundaries, so do exactly what's expected.
> 
> Mostly likely I will be the first one to have time to start with the first section. I'll then go ahead and extract the features of the first section that we can discuss. We could/should ask @cooper-joe to have a look at the specs & app before we start coding.

👍. Also, as a reference I think a lot of the approach for the data-quality-app applies here as well: https://github.com/dhis2/who-data-quality-app/issues/79.

**Comment by ismay** [comment]
Note: If we write any docs they can be added to the user-guide.

**Comment by ismay** [comment]
I think we can close this now that the app has been built (it can still be improved of course, but the basics are there).
