### ISSUE TITLE
Issue with running cypress e2e tests locally

### ISSUE THREAD

**Issue by harskum** [dhis2/sms-configuration-app#290]
I have my dhis2 instance deployed at `http://localhost:9000`
![image](https://user-images.githubusercontent.com/52396256/123419784-46a80200-d5d8-11eb-95d4-315c5569c958.png)

I also have my `cypress.env.json` file correctly populated with the following values
![image](https://user-images.githubusercontent.com/52396256/123420601-5ecc5100-d5d9-11eb-8aae-f92c6fc6bc8d.png)

When I run `yarn cy:open` to run the cypress test in the current project, I see the following failure -
![image](https://user-images.githubusercontent.com/52396256/123419898-6d663880-d5d8-11eb-9cb2-e015c0b6857e.png)

Looks like it's trying to find the element `[data-test="dhis2-smsconfiguration-shared-navigationitem"]:nth-child(3)`, but after some manual inspection, I found that this element is supposed to appear after the login is complete.

When I check the network logs for when the tests runs, I see `401 Unauthorized` errors, which I am guessing could be causing the login failures.
![image](https://user-images.githubusercontent.com/52396256/123420095-b61df180-d5d8-11eb-8e17-715a55dbea56.png)
 
What's weird is, I am able to login manually in the same chrome tab in which crpress tests are run.
![image](https://user-images.githubusercontent.com/52396256/123420227-ea91ad80-d5d8-11eb-8425-d407352cbf34.png)
and this time, we can see that previously referred network entry passes, with `200` response code
![image](https://user-images.githubusercontent.com/52396256/123420298-06954f00-d5d9-11eb-9fc0-4ab67eae719a.png)

Is anyone else able to run the cypress tests in this repo? I am unable to figure out why the network call is failing with `401 Unauthorized` when the tests are run.

**Comment by Mohammer5** [comment]
@harskum Normally this should be in Jira, but one guess I can state here is:
Did you allow `localhost:9000` in the settings app (on the "access" page)?
I can run the tests later to see if the setup still works, last time I ran them, they've been working for me though

**Comment by harskum** [comment]
@Mohammer5 Yeah, seems like it's already present(I didn't add anything manually)
![image](https://user-images.githubusercontent.com/52396256/123422741-41e54d00-d5dc-11eb-8458-04da8532817a.png)

Although, while running cypress tests, I have disabled `chromeWebSecurity` completely, so anything related to `CORS` shouldn't be any issue IMO. :/ 
![image](https://user-images.githubusercontent.com/52396256/123422882-75c07280-d5dc-11eb-8ec8-f5dfca4713d8.png)

It would be great if you could try and see if the tests for you! I really would appreciate your help here!

**Comment by harskum** [comment]
Seems like I am facing the same error for another repo as well - [import-export-app](https://github.com/dhis2/import-export-app)
![image](https://user-images.githubusercontent.com/52396256/123427664-896ed780-d5e2-11eb-8865-01d08882dd0d.png)

**Comment by Mohammer5** [comment]
I just gave it a try and it worked quite flawlessly for me. `chromeWebSecurity` should not be needed, we have a cypress plugin that takes care of that. I assume you have set up the login credentials correctly (`dhis2BaseUrl`, `dhis2Username` & `dhis2Password` in the `cypress.env.json`)?

**Comment by harskum** [comment]
Hey @Mohammer5 ! Sorry, I didn't provide an update on this, but I was actually able to get this to work! There were some changes I made in the code during debugging session, which caused the above failures! Thanks for checking in!

Heads up: I am actually working on setting up an end to end ci test for this repo, so you can expect some PRs coming in. This is in accordance with a project github is working with dhis2. 
Current workflow - https://github.com/HarskumOrg/sms-configuration-app/blob/master/.github/workflows/main.yml

**Comment by Mohammer5** [comment]
@harskum no worries. I've been in the meeting yesterday, looking forward to the PRs!
If you need help with the sms config app, just let me know, I'm more than happy to help :smile:
