### ISSUE TITLE
Duplicate ids in sms list causing console errors

### ISSUE THREAD

**Issue by ismay** [dhis2/sms-configuration-app#52]
<img width="1280" alt="Screenshot 2020-09-10 at 10 47 17" src="https://user-images.githubusercontent.com/7355199/92704238-1a760a00-f353-11ea-85e4-f3a6f58f4d72.png">

Backend issue: https://jira.dhis2.org/browse/DHIS2-9480

**Comment by mediremi** [comment]
Issue was fixed by https://github.com/dhis2/dhis2-core/pull/7208
